/* ============================================================
   js/productos-data.js — Hankel Instruments
   ------------------------------------------------------------
   ARCHIVO GENERADO AUTOMÁTICAMENTE. NO LO EDITES A MANO.

   Para actualizar el catálogo:
     1. Edita el Excel maestro (MASTER_STOCK_INTEGRADO.xlsx)
     2. Ejecuta:  python tools/generar_productos.py
     3. Sube el archivo generado a GitHub

   Cualquier cambio hecho aquí se perderá en la próxima
   generación. Los precios están en soles, sin decimales.
   Generado: 12/08/2026 21:39
   Productos: 73
   ============================================================ */

window.PRODUCTS_DATA = [
  {
    "id": "esp-01s-esp8266",
    "sku": "HK-IOT-032",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "ESP-01",
    "familia_soc": "ESP8266",
    "nombre": "ESP-01S ESP8266",
    "imagen": "HI01",
    "soc": "Espressif ESP8266EX",
    "tipo": "Módulo Wi-Fi serie",
    "precio": 11,
    "stock": 0,
    "cpu": "Tensilica L106 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "80",
    "ram": "~50 KB RAM de usuario",
    "flash": "1 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n",
    "perifericos": "2 GPIO accesibles; UART; header de 8 pines; LED de estado; requiere adaptador USB-TTL y alimentación de 3.3 V",
    "ide": "Arduino IDE, ESP-IDF, AT firmware",
    "ficha": "Módulo Wi-Fi de menor costo del ecosistema Espressif. Integra el ESP8266EX a 80 MHz con 1 MB de Flash en un formato de 8 pines pensado para dar conectividad a un microcontrolador anfitrión por UART, o para operar de forma autónoma en tareas simples.",
    "link": "https://www.espressif.com/en/products/socs/esp8266ex"
  },
  {
    "id": "digispark-attiny85",
    "sku": "HK-MCU-007",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Genérico / OEM",
    "familia": "Digispark",
    "familia_soc": "Microchip AVR",
    "nombre": "Digispark ATtiny85",
    "imagen": "HI02",
    "soc": "Microchip ATtiny85",
    "tipo": "MCU compacto con USB",
    "precio": 14,
    "stock": 0,
    "cpu": "AVR 8-bit",
    "nucleos": "1",
    "frecuencia_mhz": "16",
    "ram": "512 B SRAM",
    "flash": "8 KB Flash (6 KB útiles tras bootloader)",
    "conectividad_principal": "Sin radio; USB por software",
    "perifericos": "6 GPIO; ADC de 10 bits; PWM; I2C/SPI por software; conector USB-A integrado en el PCB; LED de usuario",
    "ide": "Arduino IDE (core Digistump)",
    "ficha": "Placa mínima basada en ATtiny85 de 8 bits a 16 MHz. Su conector USB-A está formado por el propio PCB y la comunicación USB se emula por software, lo que la hace apta para dispositivos HID muy simples y automatismos de bajo costo.",
    "link": "https://github.com/digistump/DigistumpArduino"
  },
  {
    "id": "esp8266-wemos-d1-mini",
    "sku": "HK-IOT-033",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Wemos / Lolin",
    "familia": "D1 Mini",
    "familia_soc": "ESP8266",
    "nombre": "ESP8266 Wemos D1 Mini",
    "imagen": "HI03",
    "soc": "Espressif ESP8266EX (ESP-12F)",
    "tipo": "MCU inalámbrico compacto",
    "precio": 19,
    "stock": 0,
    "cpu": "Tensilica L106 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "80",
    "ram": "~50 KB RAM de usuario",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n",
    "perifericos": "11 GPIO digitales; 1 entrada analógica; I2C/SPI/UART; micro-USB con CH340; compatible con el ecosistema de shields D1 mini",
    "ide": "Arduino IDE, ESP-IDF, MicroPython, ESPHome",
    "ficha": "La placa Wi-Fi de menor costo con USB integrado. ESP8266EX a 80 MHz con 4 MB de Flash en formato de 34×25 mm, con amplio catálogo de shields apilables. Es la opción de referencia para nodos de domótica y sensores conectados.",
    "link": "https://www.wemos.cc/en/latest/d1/d1_mini.html"
  },
  {
    "id": "ch32v003-dev-board",
    "sku": "HK-MCU-008",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "WCH",
    "familia": "CH32V",
    "familia_soc": "WCH CH32V (RISC-V)",
    "nombre": "CH32V003 dev board",
    "imagen": "HI04",
    "soc": "WCH CH32V003F4P6",
    "tipo": "MCU compacto RISC-V",
    "precio": 21,
    "stock": 0,
    "cpu": "RISC-V RV32EC (QingKe V2A)",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "2 KB SRAM",
    "flash": "16 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "18 GPIO según encapsulado; ADC de 10 bits; PWM; I2C/SPI/USART; depuración por línea única (SDI); operación de 2.7 a 5.5 V",
    "ide": "MounRiver Studio, PlatformIO, ch32v003fun",
    "ficha": "Microcontrolador RISC-V al costo de un 8 bits tradicional. El CH32V003 opera a 48 MHz con 16 KB de Flash y 2 KB de SRAM, con depuración por una sola línea. Es una alternativa económica al AVR en producción de volumen.",
    "link": "https://www.wch-ic.com/products/CH32V003.html"
  },
  {
    "id": "esp32-c3-supermini",
    "sku": "HK-IOT-009",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "SuperMini",
    "familia_soc": "ESP32-C3",
    "nombre": "ESP32-C3 SuperMini",
    "imagen": "HI05",
    "soc": "Espressif ESP32-C3FH4",
    "tipo": "MCU inalámbrico compacto",
    "precio": 22,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "11 GPIO utilizables; ADC de 12 bits; I2C/SPI/UART; USB-C nativo (Serial/JTAG); LED en GPIO8; botones Boot/Reset; antena cerámica",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "Placa ESP32-C3 en formato ultracompacto de 22×18 mm. CPU RISC-V a 160 MHz con 400 KB de SRAM y 4 MB de Flash, Wi-Fi y Bluetooth 5 LE. Incorpora USB-C nativo sin conversor serie externo, lo que reduce el costo por nodo en despliegues de sensores.",
    "link": "https://www.espboards.dev/esp32/esp32-c3-super-mini/"
  },
  {
    "id": "stm32f103c8t6-blue-pill",
    "sku": "HK-MCU-009",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "WeAct Studio",
    "familia": "Blue Pill",
    "familia_soc": "STM32",
    "nombre": "STM32F103C8T6 Blue Pill",
    "imagen": "HI06",
    "soc": "STMicroelectronics STM32F103C8T6",
    "tipo": "MCU de desarrollo",
    "precio": 24,
    "stock": 0,
    "cpu": "Arm Cortex-M3",
    "nucleos": "1",
    "frecuencia_mhz": "72",
    "ram": "20 KB SRAM",
    "flash": "64 KB Flash",
    "conectividad_principal": "Sin radio; USB 2.0 FS",
    "perifericos": "37 GPIO; ADC de 12 bits; 3× USART; 2× SPI; 2× I2C; CAN; USB device; micro-USB; cabecera SWD para ST-LINK",
    "ide": "STM32CubeIDE, Arduino IDE (core STM32), PlatformIO, Keil",
    "ficha": "Placa de desarrollo clásica del STM32F103, Cortex-M3 a 72 MHz con 64 KB de Flash y 20 KB de SRAM. Ofrece periféricos industriales como CAN y USB device a costo mínimo, y es la referencia habitual en formación en arquitectura Arm.",
    "link": "https://www.st.com/en/microcontrollers-microprocessors/stm32f103c8.html"
  },
  {
    "id": "arduino-nano-v3-ch340",
    "sku": "HK-MCU-010",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Genérico / OEM",
    "familia": "Arduino Nano",
    "familia_soc": "Microchip AVR",
    "nombre": "Arduino Nano V3 (CH340)",
    "imagen": "HI07",
    "soc": "Microchip ATmega328P",
    "tipo": "MCU de desarrollo compatible",
    "precio": 24,
    "stock": 0,
    "cpu": "AVR 8-bit",
    "nucleos": "1",
    "frecuencia_mhz": "16",
    "ram": "2 KB SRAM",
    "flash": "32 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "14 I/O digitales (6 PWM); 8 entradas analógicas; ADC de 10 bits; I2C/SPI/UART; mini-USB o USB-C con CH340; formato DIP de 30 pines",
    "ide": "Arduino IDE, PlatformIO",
    "ficha": "Versión compatible del Arduino Nano con ATmega328P a 16 MHz. Formato DIP apto para zócalo y protoboard, con la compatibilidad total de bibliotecas del ecosistema Arduino. Sigue siendo la plataforma de entrada más extendida en educación técnica.",
    "link": "https://docs.arduino.cc/hardware/nano"
  },
  {
    "id": "nodemcu-esp8266-v3-ch340",
    "sku": "HK-IOT-034",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "NodeMCU",
    "familia_soc": "ESP8266",
    "nombre": "NodeMCU ESP8266 V3 (CH340)",
    "imagen": "HI08",
    "soc": "Espressif ESP8266EX (ESP-12E)",
    "tipo": "Kit de desarrollo Wi-Fi",
    "precio": 26,
    "stock": 0,
    "cpu": "Tensilica L106 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "80",
    "ram": "~50 KB RAM de usuario",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n",
    "perifericos": "11 GPIO; 1 entrada analógica; I2C/SPI/UART; micro-USB con CH340; botones Flash/Reset; doble hilera para protoboard",
    "ide": "Arduino IDE, ESP-IDF, MicroPython, ESPHome, Lua NodeMCU",
    "ficha": "Formato de doble hilera del ESP8266 con USB y regulador integrados. ESP-12E a 80 MHz con 4 MB de Flash, listo para protoboard sin adaptadores. Es la plataforma Wi-Fi de entrada con mayor cantidad de tutoriales disponibles.",
    "link": "https://www.espressif.com/en/products/socs/esp8266ex"
  },
  {
    "id": "raspberry-pi-pico",
    "sku": "HK-MCU-011",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Raspberry Pi",
    "familia": "Raspberry Pi Pico",
    "familia_soc": "RP2040",
    "nombre": "Raspberry Pi Pico",
    "imagen": "HI09",
    "soc": "Raspberry Pi RP2040",
    "tipo": "MCU de desarrollo",
    "precio": 26,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M0+",
    "nucleos": "2",
    "frecuencia_mhz": "133",
    "ram": "264 KB SRAM",
    "flash": "2 MB QSPI Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "26 GPIO; 3 ADC; 2× UART, 2× SPI, 2× I2C; 16 PWM; 8 máquinas PIO; USB 1.1; pines castellados para montaje SMD",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython, Arduino IDE",
    "ficha": "Versión sin radio del Pico. RP2040 dual-core a 133 MHz con 264 KB de SRAM y 2 MB de Flash. Sus ocho máquinas de estado PIO permiten implementar protocolos a medida por hardware, algo poco común en este rango de precio.",
    "link": "https://www.raspberrypi.com/products/raspberry-pi-pico/"
  },
  {
    "id": "rp2040-zero",
    "sku": "HK-MCU-005",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Waveshare",
    "familia": "Zero (Waveshare)",
    "familia_soc": "RP2040",
    "nombre": "RP2040-Zero",
    "imagen": "HI10",
    "soc": "Raspberry Pi RP2040",
    "tipo": "MCU compacto",
    "precio": 28,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M0+",
    "nucleos": "2",
    "frecuencia_mhz": "133",
    "ram": "264 KB SRAM",
    "flash": "2 MB onboard Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "20 GPIO expuestos; 2× SPI, 2× I2C, 2× UART; ADC de 12 bits; PWM; PIO; USB Type-C; LED RGB WS2812",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython",
    "ficha": "Waveshare RP2040-Zero es una placa compacta basada en RP2040 dual-core Cortex-M0+ a 133 MHz, con 264 KB de SRAM y 2 MB de Flash. Expone 20 GPIO en el pequeño formato de la placa e incluye USB-C, ADC, PWM, PIO y un LED RGB WS2812; no dispone de Wi-Fi integrado.",
    "link": "https://www.waveshare.com/wiki/RP2040-Zero"
  },
  {
    "id": "pro-micro-atmega32u4",
    "sku": "HK-MCU-012",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Genérico / OEM",
    "familia": "Pro Micro",
    "familia_soc": "Microchip AVR",
    "nombre": "Pro Micro ATmega32U4",
    "imagen": "HI11",
    "soc": "Microchip ATmega32U4",
    "tipo": "MCU compacto con USB nativo",
    "precio": 28,
    "stock": 0,
    "cpu": "AVR 8-bit",
    "nucleos": "1",
    "frecuencia_mhz": "16",
    "ram": "2.5 KB SRAM",
    "flash": "32 KB Flash",
    "conectividad_principal": "Sin radio; USB 2.0 nativo",
    "perifericos": "18 I/O digitales; 9 entradas analógicas; PWM; I2C/SPI/UART; USB-C o micro-USB; soporte HID nativo (teclado y ratón)",
    "ide": "Arduino IDE, PlatformIO, QMK",
    "ficha": "Formato Pro Micro con ATmega32U4, cuyo USB nativo permite que el equipo se presente como teclado o ratón sin firmware adicional. Es la base de la mayoría de teclados mecánicos personalizados cableados.",
    "link": "https://www.sparkfun.com/products/12640"
  },
  {
    "id": "lilygo-ttgo-t-micro32",
    "sku": "HK-IOT-014",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "LILYGO",
    "familia": "TTGO",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "LILYGO TTGO T-Micro32",
    "imagen": "HI12",
    "soc": "Espressif ESP32-PICO-D4",
    "tipo": "MCU inalámbrico compacto",
    "precio": 30,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "GPIO en doble hilera; ADC/DAC; touch; I2C/SPI/UART/I2S; micro-USB con CP2104; formato reducido tipo Pro Mini",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "T-Micro32 emplea el SiP ESP32-PICO-D4, que integra el ESP32 dual-core y la Flash en un solo encapsulado. Opera a 240 MHz con 520 KB de SRAM y 4 MB de Flash, con Wi-Fi y Bluetooth Classic/BLE en una placa de huella muy reducida.",
    "link": "https://www.lilygo.cc/"
  },
  {
    "id": "weact-studio-esp32-c3",
    "sku": "HK-IOT-015",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "WeAct Studio",
    "familia": "WeAct Core",
    "familia_soc": "ESP32-C3",
    "nombre": "WeAct Studio ESP32-C3",
    "imagen": "HI13",
    "soc": "Espressif ESP32-C3FN4",
    "tipo": "MCU inalámbrico",
    "precio": 32,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "GPIO en doble hilera de 2.54 mm; ADC de 12 bits; I2C/SPI/UART; USB-C nativo; botones Boot/Reset; LED de usuario",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Placa WeAct basada en ESP32-C3, CPU RISC-V a 160 MHz con 400 KB de SRAM y 4 MB de Flash. Expone los GPIO en headers de 2.54 mm aptos para protoboard e incluye USB-C nativo, Wi-Fi y Bluetooth 5 LE.",
    "link": "https://github.com/WeActStudio"
  },
  {
    "id": "esp32-devkit-v1-nodemcu-esp-32s",
    "sku": "HK-IOT-018",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "NodeMCU",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "ESP32 DevKit V1 (NodeMCU ESP-32S)",
    "imagen": "HI14",
    "soc": "Espressif ESP32-WROOM-32",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 33,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "30 o 38 pines según variante; ADC de 12 bits; DAC; 10 touch; I2C/SPI/UART/I2S; micro-USB con CP2102 o CH340; botones Boot/EN",
    "ide": "ESP-IDF, Arduino IDE, MicroPython, PlatformIO",
    "ficha": "Placa de desarrollo ESP32 de referencia, con módulo WROOM-32 dual-core a 240 MHz, 520 KB de SRAM y 4 MB de Flash. Formato de doble hilera apto para protoboard y la base de ejemplos más amplia del ecosistema ESP32.",
    "link": "https://www.espressif.com/en/products/modules"
  },
  {
    "id": "wemos-d1-mini-esp32",
    "sku": "HK-IOT-016",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Wemos / Lolin",
    "familia": "D1 Mini",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "Wemos D1 Mini ESP32",
    "imagen": "HI15",
    "soc": "Espressif ESP32-WROOM-32",
    "tipo": "MCU inalámbrico compacto",
    "precio": 34,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "GPIO compatibles con el formato D1 mini; ADC; DAC; touch; I2C/SPI/UART/I2S; micro-USB con CH340; compatible con shields D1 mini",
    "ide": "ESP-IDF, Arduino IDE, MicroPython, PlatformIO",
    "ficha": "Versión ESP32 del formato D1 mini, con módulo WROOM-32 dual-core a 240 MHz, 520 KB de SRAM y 4 MB de Flash. Mantiene la compatibilidad mecánica con los shields del ecosistema D1 mini, lo que acelera el prototipado.",
    "link": "https://www.wemos.cc/"
  },
  {
    "id": "lolin-s2-mini",
    "sku": "HK-IOT-013",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Wemos / Lolin",
    "familia": "Lolin Mini",
    "familia_soc": "ESP32-S2",
    "nombre": "Lolin S2 Mini",
    "imagen": "HI16",
    "soc": "Espressif ESP32-S2FN4R2",
    "tipo": "MCU inalámbrico compacto",
    "precio": 34,
    "stock": 0,
    "cpu": "Xtensa LX7 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "240",
    "ram": "320 KB SRAM + 2 MB PSRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; sin Bluetooth",
    "perifericos": "27 GPIO; ADC de 13 bits; DAC; USB-C con OTG nativo; touch capacitivo; I2C/SPI/UART/I2S; formato compatible con LOLIN mini shields",
    "ide": "ESP-IDF, Arduino IDE, MicroPython, CircuitPython",
    "ficha": "Lolin S2 Mini utiliza el ESP32-S2 de un núcleo Xtensa LX7 a 240 MHz, con 320 KB de SRAM, 2 MB de PSRAM y 4 MB de Flash. Ofrece USB OTG nativo y 27 GPIO en formato reducido; no incorpora Bluetooth, por lo que se orienta a aplicaciones exclusivamente Wi-Fi.",
    "link": "https://www.wemos.cc/en/latest/s2/s2_mini.html"
  },
  {
    "id": "rp2350-zero-waveshare",
    "sku": "HK-MCU-013",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Waveshare",
    "familia": "Zero (Waveshare)",
    "familia_soc": "RP2350",
    "nombre": "RP2350-Zero (Waveshare)",
    "imagen": "HI17",
    "soc": "Raspberry Pi RP2350",
    "tipo": "MCU compacto",
    "precio": 36,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M33 / dual Hazard3 RISC-V (seleccionable)",
    "nucleos": "2",
    "frecuencia_mhz": "150",
    "ram": "520 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "29 GPIO (20 en headers + 9 castellados); ADC; PWM; PIO; USB-C; LED RGB WS2812; formato 23.5×18 mm",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython, Arduino IDE",
    "ficha": "Versión compacta del RP2350 con núcleos Arm Cortex-M33 o Hazard3 RISC-V seleccionables por software. Integra 520 KB de SRAM y 4 MB de Flash en 23.5×18 mm, con pines castellados para montaje directo en placa base.",
    "link": "https://www.waveshare.com/wiki/RP2350-Zero"
  },
  {
    "id": "pro-micro-nrf52840",
    "sku": "HK-MCU-006",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Genérico / OEM",
    "familia": "Pro Micro",
    "familia_soc": "Nordic nRF52",
    "nombre": "Pro Micro NRF52840",
    "imagen": "HI18",
    "soc": "Nordic nRF52840",
    "tipo": "MCU inalámbrico compacto (compatible Pro Micro)",
    "precio": 36,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "64",
    "ram": "256 KB RAM",
    "flash": "1 MB Flash",
    "conectividad_principal": "Bluetooth 5.0 LE; sin Wi-Fi",
    "perifericos": "~21 GPIO en formato Pro Micro/Elite-C; ADC; PWM; SPI; I2C; UART; USB-C; carga de batería LiPo integrada",
    "ide": "Arduino IDE, Adafruit nRF52 Bootloader, Zephyr, PlatformIO",
    "ficha": "Pro Micro NRF52840 (también vendida como SuperMini nRF52840) usa el SoC Nordic nRF52840 con núcleo Arm Cortex-M4F a 64 MHz, 1 MB de Flash y 256 KB de RAM. Mantiene el pinout compatible con Arduino Pro Micro y añade Bluetooth 5.0 LE, USB-C y gestión de carga de batería LiPo.",
    "link": "https://mechboards.co.uk/products/supermini-nrf52840-ble-pro-micro"
  },
  {
    "id": "esp32-c3-con-oled-0-42",
    "sku": "HK-IOT-024",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "SuperMini",
    "familia_soc": "ESP32-C3",
    "nombre": "ESP32-C3 con OLED 0.42\"",
    "imagen": "HI19",
    "soc": "Espressif ESP32-C3FH4",
    "tipo": "MCU inalámbrico con pantalla",
    "precio": 38,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Pantalla OLED de 0.42 in 72×40 por I2C; 11 GPIO; ADC; I2C/SPI/UART; USB-C nativo; botones Boot/Reset",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "Variante del formato SuperMini con pantalla OLED de 0.42 pulgadas integrada por bus I2C. Evita añadir un display externo en aplicaciones que requieren indicación local de estado o lecturas, manteniendo el tamaño reducido.",
    "link": "https://www.espboards.dev/"
  },
  {
    "id": "esp32-c3-devkitm-1",
    "sku": "HK-IOT-017",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Espressif",
    "familia": "DevKitM",
    "familia_soc": "ESP32-C3",
    "nombre": "ESP32-C3-DevKitM-1",
    "imagen": "HI20",
    "soc": "Espressif ESP32-C3-MINI-1",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 40,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "384 KB ROM + 4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Headers de expansión de 2×15; RGB WS2812; ADC; I2C/SPI/UART; micro-USB para alimentación y USB-UART; botones Boot/Reset; antena PCB",
    "ide": "ESP-IDF, Arduino IDE",
    "ficha": "Kit oficial de Espressif para el ESP32-C3, con módulo ESP32-C3-MINI-1 de antena integrada. CPU RISC-V a 160 MHz, 400 KB de SRAM y 4 MB de Flash, con headers de expansión completos y LED RGB direccionable.",
    "link": "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c3/esp32-c3-devkitm-1/user_guide.html"
  },
  {
    "id": "esp32-s3-zero",
    "sku": "HK-IOT-020",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Waveshare",
    "familia": "Zero (Waveshare)",
    "familia_soc": "ESP32-S3",
    "nombre": "ESP32-S3 Zero",
    "imagen": "HI21",
    "soc": "Espressif ESP32-S3FH4R2",
    "tipo": "MCU inalámbrico compacto",
    "precio": 43,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 2 MB PSRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE + Mesh",
    "perifericos": "Pines castellados; hasta 33 GPIO; ADC; I2C/SPI/UART/I2S; USB-C nativo; LED RGB WS2812; formato 23.5×18 mm",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "ESP32-S3 Zero de Waveshare, con procesador dual Xtensa LX7 a 240 MHz, 512 KB de SRAM, 2 MB de PSRAM y 4 MB de Flash. Los pines castellados permiten soldarla directamente sobre una placa base en productos de serie.",
    "link": "https://www.waveshare.com/wiki/ESP32-S3-Zero"
  },
  {
    "id": "weact-esp32-c6",
    "sku": "HK-IOT-019",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "WeAct Studio",
    "familia": "WeAct Core",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "WeAct ESP32-C6",
    "imagen": "HI22",
    "soc": "Espressif ESP32-C6",
    "tipo": "MCU inalámbrico IoT",
    "precio": 45,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "512 KB SRAM",
    "flash": "320 KB ROM + 4 MB Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE; IEEE 802.15.4 (Thread/Zigbee)",
    "perifericos": "GPIO en doble hilera; ADC de 12 bits; I2C/SPI/UART; USB-C nativo; LED RGB; botones Boot/Reset",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Placa WeAct con ESP32-C6, CPU RISC-V a 160 MHz y 512 KB de SRAM. Incorpora Wi-Fi 6, Bluetooth 5 LE e IEEE 802.15.4, lo que habilita Thread y Matter a costo de placa básica.",
    "link": "https://github.com/WeActStudio"
  },
  {
    "id": "esp32-cam-ov2640",
    "sku": "HK-IOT-021",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "ESP32-CAM",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "ESP32-CAM (OV2640)",
    "imagen": "HI23",
    "soc": "Espressif ESP32-S (ESP32-D0WD)",
    "tipo": "MCU inalámbrico con cámara",
    "precio": 45,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM + 4 MB PSRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "Cámara OV2640 de 2 MP incluida; ranura microSD; LED flash; 9 GPIO accesibles; UART para programación (requiere adaptador USB-TTL externo)",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Módulo de cámara Wi-Fi basado en ESP32 dual-core a 240 MHz, con 4 MB de PSRAM necesarios para el búfer de imagen. Incluye sensor OV2640 de 2 MP y ranura microSD. No integra puerto USB: la programación se realiza mediante un adaptador USB-TTL externo.",
    "link": "https://www.espressif.com/en/products/devkits"
  },
  {
    "id": "stm32f411-black-pill",
    "sku": "HK-MCU-014",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "WeAct Studio",
    "familia": "Black Pill",
    "familia_soc": "STM32",
    "nombre": "STM32F411 Black Pill",
    "imagen": "HI24",
    "soc": "STMicroelectronics STM32F411CEU6",
    "tipo": "MCU de desarrollo",
    "precio": 45,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "100",
    "ram": "128 KB SRAM",
    "flash": "512 KB Flash",
    "conectividad_principal": "Sin radio; USB 2.0 OTG FS",
    "perifericos": "32 GPIO; ADC de 12 bits; 3× USART; 5× SPI/I2S; 3× I2C; USB OTG; USB-C; cabecera SWD; zócalo para memoria SPI Flash externa",
    "ide": "STM32CubeIDE, Arduino IDE (core STM32), PlatformIO, Keil, MicroPython",
    "ficha": "Sucesora de la Blue Pill con Cortex-M4F a 100 MHz, unidad de punto flotante, 512 KB de Flash y 128 KB de SRAM. Incorpora USB-C, USB OTG y un zócalo para Flash SPI adicional, adecuada para procesamiento de señal e interfaces de audio.",
    "link": "https://www.st.com/en/microcontrollers-microprocessors/stm32f411ce.html"
  },
  {
    "id": "esp32-c6-supermini",
    "sku": "HK-IOT-035",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "SuperMini",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "ESP32-C6 SuperMini",
    "imagen": "HI25",
    "soc": "Espressif ESP32-C6",
    "tipo": "MCU inalámbrico compacto",
    "precio": 49,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "512 KB SRAM",
    "flash": "320 KB ROM + 4 MB Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE; IEEE 802.15.4 (Thread/Zigbee)",
    "perifericos": "Pines castellados; hasta 15 GPIO; ADC de 12 bits; I2C/SPI/UART; USB-C nativo; LED de usuario; formato 22×18 mm",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "Formato SuperMini con ESP32-C6: suma Wi-Fi 6, Bluetooth 5 LE e IEEE 802.15.4 para Thread y Matter en 22×18 mm. Es la vía de menor costo para incorporar Matter a un producto conectado.",
    "link": "https://www.espboards.dev/"
  },
  {
    "id": "raspberry-pi-pico-2",
    "sku": "HK-MCU-015",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Raspberry Pi",
    "familia": "Raspberry Pi Pico",
    "familia_soc": "RP2350",
    "nombre": "Raspberry Pi Pico 2",
    "imagen": "HI26",
    "soc": "Raspberry Pi RP2350",
    "tipo": "MCU de desarrollo",
    "precio": 52,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M33 / dual Hazard3 RISC-V (seleccionable)",
    "nucleos": "2",
    "frecuencia_mhz": "150",
    "ram": "520 KB SRAM",
    "flash": "4 MB QSPI Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "26 GPIO; 4 ADC; 2× UART, 2× SPI, 2× I2C; PWM; 12 máquinas PIO; USB 1.1; arranque seguro y almacenamiento de claves (Arm TrustZone)",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython, Arduino IDE",
    "ficha": "Segunda generación del Pico, con RP2350 a 150 MHz y arquitectura conmutable entre Cortex-M33 y RISC-V. Añade funciones de seguridad (TrustZone, arranque firmado) ausentes en el RP2040, útiles para producto comercial.",
    "link": "https://www.raspberrypi.com/products/raspberry-pi-pico-2/"
  },
  {
    "id": "lolin-s3-mini",
    "sku": "HK-IOT-022",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Wemos / Lolin",
    "familia": "Lolin Mini",
    "familia_soc": "ESP32-S3",
    "nombre": "Lolin S3 Mini",
    "imagen": "HI27",
    "soc": "Espressif ESP32-S3FH4R2",
    "tipo": "MCU inalámbrico compacto",
    "precio": 54,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 2 MB PSRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE + Mesh",
    "perifericos": "27 GPIO; ADC; touch capacitivo; I2C/SPI/UART/I2S; USB-C con OTG nativo; LED RGB; compatible con shields LOLIN mini",
    "ide": "ESP-IDF, Arduino IDE, MicroPython, CircuitPython",
    "ficha": "Lolin S3 Mini integra el ESP32-S3 dual-core Xtensa LX7 a 240 MHz con 2 MB de PSRAM, aportando aceleración vectorial para inferencia en el borde. Conserva el formato y la compatibilidad de shields de la línea LOLIN mini.",
    "link": "https://www.wemos.cc/en/latest/s3/s3_mini.html"
  },
  {
    "id": "seeed-xiao-ra4m1",
    "sku": "HK-MCU-001",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Seeed Studio",
    "familia": "XIAO",
    "familia_soc": "Renesas RA",
    "nombre": "Seeed XIAO RA4M1",
    "imagen": "HI28",
    "soc": "Renesas RA4M1 (R7FA4M1AB3CNE)",
    "tipo": "MCU compacto",
    "precio": 55,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "32 KB SRAM",
    "flash": "256 KB Flash + 8 KB Data Flash",
    "conectividad_principal": "Sin radio; CAN y USB 2.0",
    "perifericos": "19 GPIO; 6 entradas analógicas; 2× I2C, 2× UART, 2× SPI; ADC de 14 bits; DAC de 12 bits; CAN; USB-C; gestión/carga de batería",
    "ide": "Arduino IDE, MicroPython, PlatformIO",
    "ficha": "Placa XIAO basada en Renesas RA4M1, con núcleo Arm Cortex-M4F a 48 MHz, 256 KB de Flash y 32 KB de SRAM. Expone 19 GPIO, ADC de 14 bits, DAC de 12 bits, CAN, USB 2.0 y buses I2C/UART/SPI; integra gestión de batería en el formato compacto XIAO.",
    "link": "https://wiki.seeedstudio.com/getting_started_xiao_ra4m1/"
  },
  {
    "id": "lilygo-t-oi-plus",
    "sku": "HK-IOT-023",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "LILYGO",
    "familia": "T-OI",
    "familia_soc": "ESP32-C3",
    "nombre": "LILYGO T-OI PLUS",
    "imagen": "HI29",
    "soc": "Espressif ESP32-C3FH4",
    "tipo": "MCU inalámbrico con portapilas",
    "precio": 56,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Portapilas 16340 integrado con circuito de carga; GPIO en doble hilera; ADC; I2C/SPI/UART; USB-C; interruptor de alimentación",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "T-OI PLUS combina el ESP32-C3 RISC-V a 160 MHz con un portapilas 16340 y su circuito de carga integrado. Está orientada a nodos autónomos alimentados por batería recargable, sin necesidad de electrónica de gestión externa.",
    "link": "https://www.lilygo.cc/"
  },
  {
    "id": "ebyte-e73-nrf52832-dev-board",
    "sku": "HK-IOT-036",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Ebyte",
    "familia": "E73",
    "familia_soc": "Nordic nRF52",
    "nombre": "Ebyte E73 nRF52832 dev board",
    "imagen": "HI30",
    "soc": "Nordic nRF52832",
    "tipo": "MCU inalámbrico BLE",
    "precio": 57,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "64",
    "ram": "64 KB RAM",
    "flash": "512 KB Flash",
    "conectividad_principal": "Bluetooth 5 LE; sin Wi-Fi",
    "perifericos": "32 GPIO; ADC de 12 bits; PWM; I2C/SPI/UART; NFC; antena en PCB o conector IPEX según variante; cabecera SWD",
    "ide": "nRF Connect SDK, Zephyr, Arduino IDE, SEGGER Embedded Studio",
    "ficha": "Placa de evaluación del nRF52832, Cortex-M4F a 64 MHz con 512 KB de Flash y 64 KB de RAM. Es la entrada de menor costo al ecosistema Nordic, con consumo optimizado para sensores BLE alimentados por batería.",
    "link": "https://www.cdebyte.com/products/E73-2G4M04S1B"
  },
  {
    "id": "firebeetle-2-esp32-c6",
    "sku": "HK-IOT-001",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "DFRobot",
    "familia": "FireBeetle 2",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "FireBeetle 2 ESP32-C6",
    "imagen": "HI31",
    "soc": "Espressif ESP32-C6",
    "tipo": "MCU inalámbrico IoT",
    "precio": 61,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "512 KB SRAM",
    "flash": "320 KB ROM + 4 MB Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE; IEEE 802.15.4 (Zigbee/Thread)",
    "perifericos": "19 I/O digitales; 6 PWM; ADC de 12 bits; SPI; 3× UART; 2× I2C; I2S; USB 2.0; conector GDI; carga de batería/solar",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "FireBeetle 2 basada en ESP32-C6, con CPU RISC-V a 160 MHz, 512 KB de SRAM, 320 KB de ROM y 4 MB de Flash. Añade Wi-Fi 6, Bluetooth LE e IEEE 802.15.4 para Zigbee/Thread, además de 19 I/O digitales y múltiples buses y ADC.",
    "link": "https://wiki.dfrobot.com/dfr1075/"
  },
  {
    "id": "seeed-xiao-rp2350",
    "sku": "HK-MCU-002",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Seeed Studio",
    "familia": "XIAO",
    "familia_soc": "RP2350",
    "nombre": "Seeed XIAO RP2350",
    "imagen": "HI32",
    "soc": "Raspberry Pi RP2350",
    "tipo": "MCU compacto",
    "precio": 61,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M33 / dual Hazard3 RISC-V (seleccionable)",
    "nucleos": "2",
    "frecuencia_mhz": "150",
    "ram": "520 KB SRAM",
    "flash": "2 MB Flash onboard",
    "conectividad_principal": "Sin radio",
    "perifericos": "19 GPIO multifunción; USB-C; PIO; ADC; PWM; RGB; gestión y medición de batería",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython, Arduino IDE",
    "ficha": "XIAO basada en RP2350, capaz de usar dos núcleos Arm Cortex-M33 o dos núcleos Hazard3 RISC-V a hasta 150 MHz. Integra 520 KB de SRAM y 2 MB de Flash en la placa, con 19 GPIO y el ecosistema de periféricos/PIO del RP2350.",
    "link": "https://wiki.seeedstudio.com/getting-started-xiao-rp2350/"
  },
  {
    "id": "m5stack-stamp-c3-mate",
    "sku": "HK-IOT-025",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "M5Stack",
    "familia": "M5Stamp",
    "familia_soc": "ESP32-C3",
    "nombre": "M5Stack Stamp C3 Mate",
    "imagen": "HI33",
    "soc": "Espressif ESP32-C3FN4",
    "tipo": "MCU inalámbrico compacto",
    "precio": 62,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "400 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Pines castellados y headers incluidos; antena externa con conector; botón de usuario; LED RGB; I2C/SPI/UART; USB-C; carcasa protectora",
    "ide": "UIFlow, Arduino IDE, ESP-IDF, PlatformIO",
    "ficha": "Stamp C3 Mate emplea el ESP32-C3 RISC-V a 160 MHz en el formato Stamp de M5Stack, con pines castellados para montaje directo. Incluye antena externa, que mejora el alcance frente a las variantes de antena en PCB.",
    "link": "https://docs.m5stack.com/en/core/stamp_c3_mate"
  },
  {
    "id": "nodemcu-esp32-c6",
    "sku": "HK-IOT-026",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "NodeMCU",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "NodeMCU ESP32-C6",
    "imagen": "HI34",
    "soc": "Espressif ESP32-C6-WROOM-1",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 62,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "512 KB SRAM",
    "flash": "320 KB ROM + 8 MB Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE; IEEE 802.15.4 (Thread/Zigbee)",
    "perifericos": "Doble hilera de pines para protoboard; ADC de 12 bits; I2C/SPI/UART; USB-C nativo; LED RGB; botones Boot/Reset",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Placa en formato NodeMCU con módulo ESP32-C6-WROOM-1. Suma Wi-Fi 6, Bluetooth 5 LE e IEEE 802.15.4 sobre CPU RISC-V a 160 MHz, con 8 MB de Flash y disposición de pines apta para protoboard.",
    "link": "https://www.espressif.com/en/products/modules"
  },
  {
    "id": "milk-v-duo-256m",
    "sku": "HK-SBC-001",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Milk-V",
    "familia": "Duo",
    "familia_soc": "SOPHGO SG200x",
    "nombre": "Milk-V Duo 256M",
    "imagen": "HI35",
    "soc": "SOPHGO SG2002",
    "tipo": "SBC Linux/RTOS + TPU",
    "precio": 68,
    "stock": 0,
    "cpu": "RISC-V C906 + Arm Cortex-A53 seleccionable + 8051",
    "nucleos": "2",
    "frecuencia_mhz": "1000",
    "ram": "256 MB DRAM",
    "flash": "microSD; SD NAND según variante",
    "conectividad_principal": "Ethernet 100 Mb/s mediante PHY; sin radio integrado",
    "perifericos": "C906 principal hasta 1 GHz; C906 secundario hasta 700 MHz; A53 alternativo hasta 1 GHz; MIPI CSI; USB-C; hasta 26 GPIO; TPU INT8 de 1 TOPS",
    "ide": "Milk-V SDK, Linux, RTOS",
    "ficha": "Milk-V Duo 256M usa el SoC SG2002 con 256 MB de DRAM. El núcleo principal puede ser RISC-V C906 o Arm Cortex-A53 a 1 GHz, acompañado por otro C906 a 700 MHz y un 8051; incorpora TPU de 1 TOPS, MIPI CSI, USB y opciones de almacenamiento microSD/SD NAND.",
    "link": "https://milkv.io/duo"
  },
  {
    "id": "esp32-s3-devkitc-1-n8r2",
    "sku": "HK-IOT-027",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Espressif",
    "familia": "DevKitC",
    "familia_soc": "ESP32-S3",
    "nombre": "ESP32-S3-DevKitC-1 N8R2",
    "imagen": "HI36",
    "soc": "Espressif ESP32-S3-WROOM-1 N8R2",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 71,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 2 MB PSRAM",
    "flash": "384 KB ROM + 8 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE + Mesh",
    "perifericos": "45 GPIO programables; dos puertos USB-C (nativo y UART); ADC; I2C/SPI/UART/I2S; LED RGB WS2812; headers de expansión de 2×20",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Kit oficial de Espressif para ESP32-S3 en configuración N8R2: 8 MB de Flash y 2 MB de PSRAM. Procesador dual Xtensa LX7 a 240 MHz con instrucciones vectoriales para aceleración de redes neuronales, y doble interfaz USB para depuración.",
    "link": "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide.html"
  },
  {
    "id": "esp32-s3-devkit-n16r8",
    "sku": "HK-IOT-010",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "ESP32-S3 DevKit",
    "familia_soc": "ESP32-S3",
    "nombre": "ESP32-S3 DevKit N16R8",
    "imagen": "HI37",
    "soc": "Espressif ESP32-S3 (módulo ESP32-S3-WROOM-1 N16R8)",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 72,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 8 MB PSRAM",
    "flash": "16 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "45 GPIO programables; LED RGB WS2812; USB-C nativo + conversor CH340; ADC; SPI/I2C/UART/I2S; compatible con pinout ESP32-S3-DevKitC-1",
    "ide": "Arduino IDE, ESP-IDF, MicroPython",
    "ficha": "Este kit de desarrollo ESP32-S3-WROOM-1 N16R8 integra un procesador dual-core Xtensa LX7 a 240 MHz con 512 KB de SRAM, 8 MB de PSRAM y 16 MB de Flash. Incorpora Wi-Fi y Bluetooth 5 LE, 45 GPIO, LED RGB WS2812 y conversor USB-C con chip CH340.",
    "link": "https://www.waveshare.com/esp32-s3-dev-kit-n8r8.htm"
  },
  {
    "id": "seeed-xiao-samd21",
    "sku": "HK-MCU-003",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "Seeed Studio",
    "familia": "XIAO",
    "familia_soc": "Microchip SAM",
    "nombre": "Seeed XIAO SAMD21",
    "imagen": "HI38",
    "soc": "Microchip ATSAMD21G18A",
    "tipo": "MCU compacto",
    "precio": 74,
    "stock": 0,
    "cpu": "Arm Cortex-M0+",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "32 KB SRAM",
    "flash": "256 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "11 pines digitales; hasta 11 entradas analógicas; 10 PWM; 1 DAC; I2C, SPI y UART; USB-C",
    "ide": "Arduino IDE, PlatformIO, MicroPython, CircuitPython",
    "ficha": "XIAO SAMD21 utiliza el ATSAMD21G18A, un Arm Cortex-M0+ a 48 MHz con 256 KB de Flash y 32 KB de SRAM. En su formato compacto ofrece GPIO, entradas analógicas, PWM, DAC, I2C, SPI, UART y USB-C, sin conectividad inalámbrica integrada.",
    "link": "https://wiki.seeedstudio.com/Seeeduino-XIAO/"
  },
  {
    "id": "raspberry-pi-pico-w",
    "sku": "HK-IOT-002",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Raspberry Pi",
    "familia": "Raspberry Pi Pico",
    "familia_soc": "RP2040",
    "nombre": "Raspberry Pi Pico W",
    "imagen": "HI39",
    "soc": "RP2040 + Infineon CYW43439",
    "tipo": "MCU inalámbrico",
    "precio": 75,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M0+",
    "nucleos": "2",
    "frecuencia_mhz": "133",
    "ram": "264 KB SRAM",
    "flash": "2 MB QSPI Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11n; Bluetooth 5.2 / BLE",
    "perifericos": "26 GPIO; 3 ADC; 2× UART, 2× SPI, 2× I2C; 16 PWM; 8 máquinas PIO; USB 1.1; sensor de temperatura",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython",
    "ficha": "Raspberry Pi Pico W combina el RP2040 dual-core a 133 MHz con 264 KB de SRAM y 2 MB de Flash, más el CYW43439 para Wi-Fi 2.4 GHz y Bluetooth 5.2/BLE. Expone 26 GPIO y los periféricos PIO, ADC, PWM, UART, SPI e I2C del RP2040.",
    "link": "https://www.raspberrypi.com/products/raspberry-pi-pico/"
  },
  {
    "id": "nice-nano-v2-nrf52840",
    "sku": "HK-IOT-037",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "Pro Micro",
    "familia_soc": "Nordic nRF52",
    "nombre": "Nice!Nano v2 (nRF52840)",
    "imagen": "HI40",
    "soc": "Nordic nRF52840",
    "tipo": "MCU inalámbrico BLE compacto",
    "precio": 76,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "64",
    "ram": "256 KB RAM",
    "flash": "1 MB Flash + 4 MB QSPI Flash",
    "conectividad_principal": "Bluetooth 5 LE; sin Wi-Fi",
    "perifericos": "21 I/O en formato Pro Micro; ADC; PWM; I2C/SPI/UART; USB-C; circuito de carga LiPo con interruptor; soporte de firmware ZMK",
    "ide": "Arduino IDE, ZMK, nRF Connect SDK, CircuitPython",
    "ficha": "Controlador inalámbrico en formato Pro Micro con nRF52840 y gestión de batería LiPo integrada. Es el estándar de facto para teclados mecánicos inalámbricos con firmware ZMK, con demanda sostenida en esa comunidad.",
    "link": "https://nicekeyboards.com/nice-nano/"
  },
  {
    "id": "raspberry-pi-pico-2-w",
    "sku": "HK-IOT-003",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Raspberry Pi",
    "familia": "Raspberry Pi Pico",
    "familia_soc": "RP2350",
    "nombre": "Raspberry Pi Pico 2 W",
    "imagen": "HI41",
    "soc": "RP2350 + Infineon CYW43439",
    "tipo": "MCU inalámbrico",
    "precio": 79,
    "stock": 0,
    "cpu": "Dual Arm Cortex-M33 / dual Hazard3 RISC-V (seleccionable)",
    "nucleos": "2",
    "frecuencia_mhz": "150",
    "ram": "520 KB SRAM",
    "flash": "4 MB QSPI Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11n; Bluetooth 5.2 / BLE",
    "perifericos": "26 GPIO; 3 ADC; 2× UART, 2× SPI, 2× I2C; PWM; 12 máquinas PIO; USB 1.1; funciones de seguridad del RP2350",
    "ide": "Raspberry Pi Pico C/C++ SDK, MicroPython",
    "ficha": "Pico 2 W incorpora RP2350 a 150 MHz con arquitectura dual Cortex-M33 o dual Hazard3 RISC-V seleccionable, 520 KB de SRAM y 4 MB de Flash. El CYW43439 aporta Wi-Fi 2.4 GHz y Bluetooth 5.2/BLE.",
    "link": "https://www.raspberrypi.com/products/raspberry-pi-pico-2/"
  },
  {
    "id": "esp32-s3-cam-n16r8",
    "sku": "HK-IOT-011",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Genérico / OEM",
    "familia": "ESP32-S3 DevKit",
    "familia_soc": "ESP32-S3",
    "nombre": "ESP32-S3 CAM N16R8",
    "imagen": "HI42",
    "soc": "Espressif ESP32-S3 (módulo ESP32-S3-WROOM-1 N16R8)",
    "tipo": "Kit de desarrollo MCU inalámbrico con cámara",
    "precio": 84,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 8 MB PSRAM",
    "flash": "16 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Conector para cámara OV2640 u OV5640; GPIO; USB-C; ADC; SPI/I2C/UART/I2S",
    "ide": "Arduino IDE, ESP-IDF, MicroPython",
    "ficha": "Esta placa de desarrollo ESP32-S3 N16R8 añade un conector de cámara compatible con módulos OV2640 o OV5640 al mismo SoC dual-core Xtensa LX7 a 240 MHz, con 512 KB de SRAM, 8 MB de PSRAM y 16 MB de Flash. Incluye Wi-Fi y Bluetooth 5 LE, orientada a aplicaciones de visión por computador y reconocimiento de imágenes en el borde.",
    "link": "https://www.robotics.org.za/ESP32-S3-N16R8"
  },
  {
    "id": "weact-esp32-s3-core",
    "sku": "HK-IOT-028",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "WeAct Studio",
    "familia": "WeAct Core",
    "familia_soc": "ESP32-S3",
    "nombre": "WeAct ESP32-S3 Core",
    "imagen": "HI43",
    "soc": "Espressif ESP32-S3-WROOM-1",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 87,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + PSRAM según variante",
    "flash": "8 o 16 MB Flash según variante",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE + Mesh",
    "perifericos": "GPIO en doble hilera; USB-C nativo; ADC; I2C/SPI/UART/I2S; LED RGB; botones Boot/Reset; conector de batería",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "Placa WeAct con módulo ESP32-S3-WROOM-1, dual Xtensa LX7 a 240 MHz. Disponible en distintas combinaciones de Flash y PSRAM, con USB-C nativo y conector de batería para aplicaciones portátiles.",
    "link": "https://github.com/WeActStudio"
  },
  {
    "id": "stm32g474ce",
    "sku": "HK-MCU-004",
    "seccion": "mcu",
    "categoria": "MCU / Desarrollo",
    "marca": "STMicroelectronics",
    "familia": "STM32 (chip)",
    "familia_soc": "STM32",
    "nombre": "STM32G474CE",
    "imagen": "HI44",
    "soc": "STMicroelectronics STM32G474CE",
    "tipo": "MCU de señal mixta/control",
    "precio": 93,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "170",
    "ram": "128 KB SRAM",
    "flash": "512 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "ADC de 12 bits de alta velocidad; DAC; comparadores y op-amps; FDCAN; USB FS/UCPD; I2C, SPI, UART/USART; temporizadores de alta resolución",
    "ide": "STM32CubeIDE, STM32CubeMX, IAR, Keil",
    "ficha": "STM32G474CE es un microcontrolador Arm Cortex-M4F a 170 MHz con 512 KB de Flash y 128 KB de SRAM. Está orientado a control y señal mixta, con ADC/DAC, comparadores, amplificadores operacionales, temporizadores de alta resolución, FDCAN, USB y buses serie.",
    "link": "https://www.st.com/en/microcontrollers-microprocessors/stm32g474ce.html"
  },
  {
    "id": "freenove-esp32-s3-wroom-cam",
    "sku": "HK-IOT-029",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Freenove",
    "familia": "Freenove CAM",
    "familia_soc": "ESP32-S3",
    "nombre": "Freenove ESP32-S3 WROOM CAM",
    "imagen": "HI45",
    "soc": "Espressif ESP32-S3-WROOM-1 N8R8",
    "tipo": "Kit de desarrollo con cámara",
    "precio": 97,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM + 8 MB PSRAM",
    "flash": "8 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Cámara OV2640 incluida; ranura microSD; 36 GPIO; USB-C; ADC; I2C/SPI/UART/I2S; headers de expansión; documentación y ejemplos oficiales",
    "ide": "ESP-IDF, Arduino IDE, MicroPython",
    "ficha": "Placa Freenove con ESP32-S3-WROOM-1 N8R8: 8 MB de Flash y 8 MB de PSRAM, holgura suficiente para procesamiento de imagen. Incluye cámara OV2640, ranura microSD y USB-C, con biblioteca de ejemplos documentada para visión.",
    "link": "https://github.com/Freenove"
  },
  {
    "id": "heltec-wifi-kit-32",
    "sku": "HK-IOT-030",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Heltec",
    "familia": "WiFi Kit",
    "familia_soc": "ESP32-S3",
    "nombre": "Heltec WiFi Kit 32",
    "imagen": "HI46",
    "soc": "Espressif ESP32-S3FN8",
    "tipo": "MCU inalámbrico con pantalla",
    "precio": 99,
    "stock": 0,
    "cpu": "Dual Xtensa LX7",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "512 KB SRAM",
    "flash": "8 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 5 LE",
    "perifericos": "Pantalla OLED de 0.96 in 128×64 integrada; gestión y carga de batería LiPo; USB-C; GPIO en doble hilera; ADC; I2C/SPI/UART",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "WiFi Kit 32 integra el ESP32-S3 dual-core a 240 MHz con pantalla OLED de 0.96 pulgadas y circuito de carga de batería LiPo en la misma placa. Está orientada a nodos portátiles que requieren indicación local sin hardware adicional.",
    "link": "https://heltec.org/project/wifi-kit-32-v3/"
  },
  {
    "id": "lilygo-ttgo-t-display",
    "sku": "HK-IOT-031",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "LILYGO",
    "familia": "T-Display",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "LILYGO TTGO T-Display",
    "imagen": "HI47",
    "soc": "Espressif ESP32-D0WDQ6",
    "tipo": "MCU inalámbrico con pantalla TFT",
    "precio": 107,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM + 8 MB PSRAM",
    "flash": "16 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "Pantalla IPS de 1.14 in 135×240 con controlador ST7789; dos botones de usuario; conector de batería con carga; USB-C; GPIO en doble hilera; I2C/SPI/UART",
    "ide": "ESP-IDF, Arduino IDE, PlatformIO",
    "ficha": "T-Display combina el ESP32 dual-core a 240 MHz con una pantalla IPS a color de 1.14 pulgadas y 16 MB de Flash. Incluye conector y circuito de carga de batería, adecuada para instrumentos portátiles con interfaz gráfica.",
    "link": "https://www.lilygo.cc/products/lilygo%C2%AE-ttgo-t-display"
  },
  {
    "id": "microchip-sam-d21-curiosity-nano",
    "sku": "HK-CUR-001",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip SAM",
    "nombre": "Microchip SAM D21 Curiosity Nano",
    "imagen": "HI48",
    "soc": "Microchip SAMD21G17D",
    "tipo": "Kit de evaluación MCU",
    "precio": 114,
    "stock": 0,
    "cpu": "Arm Cortex-M0+",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "16 KB SRAM",
    "flash": "128 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "Depurador/programador integrado; Virtual COM; USB; LED y pulsador de usuario; pines de expansión; periféricos ADC, timers, I2C/SPI/UART del SAMD21",
    "ide": "MPLAB X IDE, MPLAB Harmony / MCC",
    "ficha": "SAM D21 Curiosity Nano evalúa el SAMD21G17D, un Cortex-M0+ de hasta 48 MHz con 128 KB de Flash y 16 KB de SRAM. El kit integra depurador/programador, puerto COM virtual, alimentación USB, LED/pulsador y acceso a los pines del MCU.",
    "link": "https://www.microchip.com/en-us/development-tool/dm320119"
  },
  {
    "id": "microchip-sam-e51-curiosity-nano",
    "sku": "HK-CUR-002",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip SAM",
    "nombre": "Microchip SAM E51 Curiosity Nano",
    "imagen": "HI49",
    "soc": "Microchip SAME51J20A",
    "tipo": "Kit de evaluación MCU",
    "precio": 114,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "120",
    "ram": "256 KB SRAM",
    "flash": "1 MB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "Depurador integrado; USB; LED/pulsador; pines de expansión; ADC/DAC y buses I2C/SPI/UART del SAME51",
    "ide": "MPLAB X IDE, MPLAB Harmony / MCC",
    "ficha": "SAM E51 Curiosity Nano está basada en SAME51J20A, un Cortex-M4F a 120 MHz con 1 MB de Flash y 256 KB de SRAM. La placa incorpora depurador/programador, USB, LED y pulsador de usuario y acceso directo a los periféricos del microcontrolador.",
    "link": "https://www.microchip.com/en-us/development-tool/ev76s68a"
  },
  {
    "id": "avr64dd32-curiosity-nano",
    "sku": "HK-CUR-003",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip AVR",
    "nombre": "AVR64DD32 Curiosity Nano",
    "imagen": "HI50",
    "soc": "Microchip AVR64DD32",
    "tipo": "Kit de evaluación MCU",
    "precio": 114,
    "stock": 0,
    "cpu": "AVR 8-bit",
    "nucleos": "1",
    "frecuencia_mhz": "24",
    "ram": "8 KB SRAM",
    "flash": "64 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "MVIO; ADC; DAC; UART, SPI e I2C/TWI; temporizadores; LED/pulsador; depurador integrado; tensión objetivo ajustable",
    "ide": "MPLAB X IDE, MCC, Microchip Studio",
    "ficha": "AVR64DD32 Curiosity Nano evalúa el AVR64DD32 de 8 bits a hasta 24 MHz, con 64 KB de Flash y 8 KB de SRAM. Incluye MVIO, periféricos analógicos y serie, depurador integrado, LED/pulsador y alimentación objetivo configurable.",
    "link": "https://www.microchip.com/en-us/development-tool/ev72y42a"
  },
  {
    "id": "avr64du32-curiosity-nano",
    "sku": "HK-CUR-004",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip AVR",
    "nombre": "AVR64DU32 Curiosity Nano",
    "imagen": "HI51",
    "soc": "Microchip AVR64DU32",
    "tipo": "Kit de evaluación MCU con USB",
    "precio": 114,
    "stock": 0,
    "cpu": "AVR 8-bit",
    "nucleos": "1",
    "frecuencia_mhz": "24",
    "ram": "8 KB SRAM",
    "flash": "64 KB Flash",
    "conectividad_principal": "USB 2.0 Full-Speed; sin radio",
    "perifericos": "USB FS integrado; MVIO; ADC; UART, SPI e I2C/TWI; temporizadores; depurador integrado; conectividad USB-C",
    "ide": "MPLAB X IDE, MCC, Microchip Studio",
    "ficha": "AVR64DU32 Curiosity Nano usa el AVR64DU32 de 8 bits a 24 MHz, con 64 KB de Flash y 8 KB de SRAM. A diferencia de la familia DD, la familia DU integra USB 2.0 Full-Speed; el kit expone además MVIO y los buses/periféricos del MCU.",
    "link": "https://www.microchip.com/en-us/development-tool/ev59f82a"
  },
  {
    "id": "pic32cm-curiosity-nano-touch",
    "sku": "HK-CUR-005",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip PIC",
    "nombre": "PIC32CM Curiosity Nano+ Touch",
    "imagen": "HI52",
    "soc": "Microchip PIC32CM5164JH01048",
    "tipo": "Kit de evaluación MCU + touch",
    "precio": 114,
    "stock": 0,
    "cpu": "Arm Cortex-M0+",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "64 KB SRAM",
    "flash": "512 KB Flash",
    "conectividad_principal": "CAN/LIN; sin radio",
    "perifericos": "Botón táctil; depurador integrado; USB; CAN y LIN; LED/pulsador; ADC y buses serie del PIC32CM",
    "ide": "MPLAB X IDE, MPLAB Harmony / MCC",
    "ficha": "PIC32CM JH01 Curiosity Nano+ Touch utiliza el PIC32CM5164JH01048, Cortex-M0+ a 48 MHz con 512 KB de Flash y 64 KB de SRAM. El kit añade botón táctil, depuración integrada y conectividad CAN/LIN, además del acceso a los periféricos del MCU.",
    "link": "https://www.microchip.com/en-us/development-tool/ev29g58a"
  },
  {
    "id": "dspic33-curiosity-nano",
    "sku": "HK-CUR-006",
    "seccion": "mcu",
    "categoria": "Microchip Curiosity",
    "marca": "Microchip",
    "familia": "Curiosity Nano",
    "familia_soc": "Microchip PIC",
    "nombre": "dsPIC33 Curiosity Nano",
    "imagen": "HI53",
    "soc": "Microchip dsPIC33CK64MC105",
    "tipo": "Kit de evaluación DSC",
    "precio": 114,
    "stock": 0,
    "cpu": "dsPIC33 16-bit DSC",
    "nucleos": "1",
    "frecuencia_mhz": "100",
    "ram": "8 KB RAM",
    "flash": "64 KB ECC Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "ADC de 12 bits; PWM de alta velocidad; op-amps/comparadores/DAC; buses serie; depurador integrado; LED/pulsador",
    "ide": "MPLAB X IDE, MCC",
    "ficha": "dsPIC33 Curiosity Nano está basada en dsPIC33CK64MC105, un controlador digital de señales de 16 bits que opera hasta 100 MHz, con 64 KB de Flash ECC y 8 KB de RAM. Está orientado a control digital, con ADC, PWM rápido y recursos analógicos integrados.",
    "link": "https://www.microchip.com/en-us/development-tool/ev88g73a"
  },
  {
    "id": "esp32-c6-devkitc-1",
    "sku": "HK-IOT-004",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Espressif",
    "familia": "DevKitC",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "ESP32-C6-DevKitC-1",
    "imagen": "HI54",
    "soc": "Espressif ESP32-C6 (módulo ESP32-C6-WROOM-1)",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 120,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "512 KB SRAM",
    "flash": "320 KB ROM + 8 MB SPI Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE; IEEE 802.15.4 (Thread/Zigbee)",
    "perifericos": "USB nativo y USB-UART; GPIO; ADC; SPI/I2C/UART/I2S; headers de expansión; botones Boot/Reset",
    "ide": "ESP-IDF, Arduino IDE",
    "ficha": "ESP32-C6-DevKitC-1 es la placa oficial de desarrollo para ESP32-C6, con CPU RISC-V a 160 MHz, 512 KB de SRAM y módulo con Flash SPI. Integra Wi-Fi 6, Bluetooth LE e IEEE 802.15.4 para Thread/Zigbee, además de USB y headers para los GPIO del SoC.",
    "link": "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html"
  },
  {
    "id": "seeed-xiao-mg24",
    "sku": "HK-IOT-005",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Seeed Studio",
    "familia": "XIAO",
    "familia_soc": "Silicon Labs EFR32",
    "nombre": "Seeed XIAO MG24",
    "imagen": "HI55",
    "soc": "Silicon Labs EFR32MG24",
    "tipo": "MCU inalámbrico multiprotocolo",
    "precio": 125,
    "stock": 0,
    "cpu": "Arm Cortex-M33",
    "nucleos": "1",
    "frecuencia_mhz": "78",
    "ram": "256 KB RAM",
    "flash": "1.5 MB Flash interna + 4 MB Flash onboard",
    "conectividad_principal": "Bluetooth 5.3 LE; Matter/Thread; Zigbee",
    "perifericos": "GPIO; ADC; UART/SPI/I2C; USB-C; RGB; gestión de batería; radio multiprotocolo 2.4 GHz",
    "ide": "Arduino IDE, Simplicity Studio, Zephyr / SDK Silicon Labs",
    "ficha": "XIAO MG24 usa el EFR32MG24, Cortex-M33 a 78 MHz con 256 KB de RAM y 1.5 MB de Flash interna, complementada por 4 MB de Flash en placa. Su radio 2.4 GHz soporta Bluetooth LE, Matter/Thread y Zigbee en un formato XIAO compacto.",
    "link": "https://wiki.seeedstudio.com/xiao_mg24_getting_started/"
  },
  {
    "id": "luckfox-pico",
    "sku": "HK-SBC-002",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "LuckFox",
    "familia": "LuckFox Pico",
    "familia_soc": "Rockchip RV11xx",
    "nombre": "LuckFox Pico",
    "imagen": "HI56",
    "soc": "Rockchip RV1103",
    "tipo": "SBC Linux + NPU",
    "precio": 147,
    "stock": 0,
    "cpu": "Arm Cortex-A7 + coprocesador RISC-V",
    "nucleos": "1",
    "frecuencia_mhz": "1200",
    "ram": "64 MB DDR2",
    "flash": "microSD",
    "conectividad_principal": "Sin Wi-Fi/Bluetooth; Ethernet no integrado en el modelo base",
    "perifericos": "MIPI CSI de 2 lanes; USB 2.0 host/device; 24 GPIO; NPU de 0.5 TOPS; audio/serial según pines",
    "ide": "LuckFox SDK, Buildroot, Ubuntu 22.04",
    "ficha": "LuckFox Pico base utiliza RV1103 con Cortex-A7 a 1.2 GHz, coprocesador RISC-V, 64 MB de DDR2 y NPU de 0.5 TOPS. Dispone de cámara MIPI CSI, USB, microSD y GPIO; el modelo base no incorpora radio inalámbrica ni Ethernet integrado.",
    "link": "https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-RV1103/"
  },
  {
    "id": "raspberry-pi-zero-2-w",
    "sku": "HK-SBC-004",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Raspberry Pi",
    "familia": "Raspberry Pi Zero",
    "familia_soc": "Broadcom BCM",
    "nombre": "Raspberry Pi Zero 2 W",
    "imagen": "HI57",
    "soc": "Broadcom BCM2710A1 en RP3A0 SiP",
    "tipo": "SBC Linux",
    "precio": 163,
    "stock": 0,
    "cpu": "Quad Arm Cortex-A53",
    "nucleos": "4",
    "frecuencia_mhz": "1000",
    "ram": "512 MB SDRAM",
    "flash": "microSD",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth 4.2 / BLE",
    "perifericos": "mini HDMI; micro-USB OTG; micro-USB power; CSI-2; footprint GPIO de 40 pines; decodificación H.264",
    "ide": "Raspberry Pi OS, Linux",
    "ficha": "Raspberry Pi Zero 2 W integra el SiP RP3A0 con CPU quad-core Cortex-A53 a 1 GHz y 512 MB de SDRAM. Añade Wi-Fi 2.4 GHz y Bluetooth 4.2/BLE, microSD, mini HDMI, USB OTG, cámara CSI-2 y el footprint GPIO de 40 pines.",
    "link": "https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/"
  },
  {
    "id": "sipeed-licheerv-nano",
    "sku": "HK-SBC-003",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Sipeed",
    "familia": "LicheeRV",
    "familia_soc": "SOPHGO SG200x",
    "nombre": "Sipeed LicheeRV Nano",
    "imagen": "HI58",
    "soc": "SOPHGO SG2002",
    "tipo": "SBC Linux/RTOS + NPU",
    "precio": 167,
    "stock": 0,
    "cpu": "RISC-V C906 + Arm Cortex-A53 seleccionable + 8051",
    "nucleos": "2",
    "frecuencia_mhz": "1000",
    "ram": "256 MB DDR3",
    "flash": "microSD; SD NAND según versión",
    "conectividad_principal": "Ethernet 100 Mb/s y/o Wi-Fi 6 + Bluetooth 5.4 según versión",
    "perifericos": "C906 principal 1 GHz; C906 secundario 700 MHz; A53 alternativo 1 GHz; USB-C OTG; MIPI CSI/DSI; audio; NPU de 1 TOPS",
    "ide": "Sipeed SDK, Buildroot Linux, Debian, RTOS",
    "ficha": "LicheeRV Nano se basa en SG2002 con 256 MB DDR3. Puede ejecutar el núcleo principal RISC-V C906 o Arm Cortex-A53 a 1 GHz, acompañado por otro C906 a 700 MHz, e integra NPU de 1 TOPS. Las variantes añaden Ethernet y/o Wi-Fi 6 con Bluetooth.",
    "link": "https://wiki.sipeed.com/hardware/en/lichee/RV_Nano/1_intro.html"
  },
  {
    "id": "m5stamp-pico-diy-kit",
    "sku": "HK-IOT-006",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "M5Stack",
    "familia": "M5Stamp",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "M5Stamp Pico DIY Kit",
    "imagen": "HI59",
    "soc": "Espressif ESP32-PICO-D4",
    "tipo": "MCU inalámbrico compacto",
    "precio": 182,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM",
    "flash": "4 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz 802.11b/g/n; Bluetooth Classic + BLE",
    "perifericos": "12 GPIO; ADC/DAC; touch; SPI/I2C/UART/I2S; RGB SK6812; botón; kit con programador USB y headers",
    "ide": "UIFlow, Arduino IDE, ESP-IDF, PlatformIO",
    "ficha": "M5Stamp Pico DIY Kit se basa en el SiP ESP32-PICO-D4 dual-core a 240 MHz, con 520 KB de SRAM y 4 MB de Flash. Integra Wi-Fi y Bluetooth; el kit aporta el Stamp Pico, programador USB, headers y accesorios para prototipado.",
    "link": "https://shop.m5stack.com/products/m5stamp-pico-diy-kit"
  },
  {
    "id": "esp32-c61-devkitc-1",
    "sku": "HK-IOT-007",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "Espressif",
    "familia": "DevKitC",
    "familia_soc": "ESP32-C6 / C61",
    "nombre": "ESP32-C61-DevKitC-1",
    "imagen": "HI60",
    "soc": "Espressif ESP32-C61 (ESP32-C61-WROOM-1)",
    "tipo": "Kit de desarrollo MCU inalámbrico",
    "precio": 189,
    "stock": 0,
    "cpu": "RISC-V 32-bit",
    "nucleos": "1",
    "frecuencia_mhz": "160",
    "ram": "320 KB SRAM + 2 MB PSRAM",
    "flash": "256 KB ROM + hasta 8 MB SPI Flash",
    "conectividad_principal": "Wi-Fi 6 2.4 GHz; Bluetooth 5 LE",
    "perifericos": "USB nativo + USB-UART; GPIO; ADC; buses serie; botones Boot/Reset; RGB; headers de expansión",
    "ide": "ESP-IDF",
    "ficha": "ESP32-C61-DevKitC-1 utiliza ESP32-C61, CPU RISC-V de hasta 160 MHz. La configuración de la placa incluye SRAM interna y PSRAM externa, con Flash SPI, Wi-Fi 6 y Bluetooth LE; expone dos interfaces USB y los GPIO/periféricos del SoC.",
    "link": "https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c61/esp32-c61-devkitc-1/user_guide.html"
  },
  {
    "id": "stm32-nucleo-f401re",
    "sku": "HK-STM-001",
    "seccion": "mcu",
    "categoria": "Arduino / STM32",
    "marca": "STMicroelectronics",
    "familia": "Nucleo",
    "familia_soc": "STM32",
    "nombre": "STM32 Nucleo-F401RE",
    "imagen": "HI61",
    "soc": "STMicroelectronics STM32F401RE",
    "tipo": "Nucleo-64 MCU",
    "precio": 191,
    "stock": 0,
    "cpu": "Arm Cortex-M4F",
    "nucleos": "1",
    "frecuencia_mhz": "84",
    "ram": "96 KB SRAM",
    "flash": "512 KB Flash",
    "conectividad_principal": "Sin radio",
    "perifericos": "Headers Arduino Uno V3 y ST Morpho; ST-LINK/V2-1; USB; LED y botón de usuario; acceso a ADC, timers, SPI/I2C/UART del MCU",
    "ide": "STM32CubeIDE, STM32CubeMX, IAR, Keil",
    "ficha": "NUCLEO-F401RE incorpora STM32F401RE, Cortex-M4F a 84 MHz con 512 KB de Flash y 96 KB de SRAM. La placa Nucleo-64 añade ST-LINK/V2-1 y headers Arduino Uno V3/ST Morpho para acceder a los periféricos del MCU; no integra Wi-Fi ni Bluetooth.",
    "link": "https://www.st.com/en/evaluation-tools/nucleo-f401re.html"
  },
  {
    "id": "m5stickc-plus2",
    "sku": "HK-IOT-008",
    "seccion": "mcu",
    "categoria": "MCU IoT",
    "marca": "M5Stack",
    "familia": "M5Stick",
    "familia_soc": "ESP32 (Xtensa)",
    "nombre": "M5StickC PLUS2",
    "imagen": "HI62",
    "soc": "Espressif ESP32-PICO-V3-02",
    "tipo": "Dispositivo MCU IoT con pantalla",
    "precio": 227,
    "stock": 0,
    "cpu": "Dual Xtensa LX6",
    "nucleos": "2",
    "frecuencia_mhz": "240",
    "ram": "520 KB SRAM + 2 MB PSRAM",
    "flash": "8 MB Flash",
    "conectividad_principal": "Wi-Fi 2.4 GHz; Bluetooth Classic + BLE",
    "perifericos": "TFT 1.14 in 135×240; IMU MPU6886; micrófono; RTC; buzzer; IR; botones; USB-C; HY2.0",
    "ide": "UIFlow 1/2, Arduino IDE, ESP-IDF, PlatformIO",
    "ficha": "M5StickC PLUS2 es un dispositivo compacto basado en ESP32-PICO-V3-02 dual-core a 240 MHz, con 8 MB de Flash y 2 MB de PSRAM. Integra Wi-Fi/Bluetooth, pantalla TFT, IMU, micrófono, RTC, buzzer, IR, botones y USB-C.",
    "link": "https://docs.m5stack.com/en/core/M5StickC%20PLUS2"
  },
  {
    "id": "arduino-uno-r4-wifi",
    "sku": "HK-ARD-001",
    "seccion": "mcu",
    "categoria": "Arduino",
    "marca": "Arduino",
    "familia": "Arduino UNO",
    "familia_soc": "ESP32-S3",
    "nombre": "Arduino UNO R4 WiFi",
    "imagen": "HI63",
    "soc": "Renesas RA4M1 + Espressif ESP32-S3-MINI-1",
    "tipo": "Placa Arduino con coprocesador inalámbrico",
    "precio": 234,
    "stock": 0,
    "cpu": "Arm Cortex-M4F + Xtensa LX7 (coprocesador)",
    "nucleos": "1",
    "frecuencia_mhz": "48",
    "ram": "32 KB SRAM (RA4M1)",
    "flash": "256 KB Flash (RA4M1) + memoria del módulo ESP32-S3",
    "conectividad_principal": "Wi-Fi 2.4 GHz; Bluetooth LE mediante ESP32-S3",
    "perifericos": "14 I/O digitales; 6 entradas analógicas; CAN; DAC 12-bit; ADC hasta 14-bit; USB-C HID; Qwiic; matriz LED 12×8",
    "ide": "Arduino IDE, Arduino Cloud",
    "ficha": "UNO R4 WiFi combina el Renesas RA4M1 Cortex-M4F a 48 MHz con 256 KB de Flash y 32 KB de SRAM, y un módulo ESP32-S3 para Wi-Fi/Bluetooth. Mantiene el formato UNO y añade CAN, DAC, ADC de mayor resolución, USB-C HID, Qwiic y matriz LED 12×8.",
    "link": "https://docs.arduino.cc/hardware/uno-r4-wifi"
  },
  {
    "id": "luckfox-pico-mini",
    "sku": "HK-SBC-010",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "LuckFox",
    "familia": "LuckFox Pico",
    "familia_soc": "Rockchip RV11xx",
    "nombre": "LuckFox Pico Mini",
    "imagen": "HI64",
    "soc": "Rockchip RV1103",
    "tipo": "SBC Linux + NPU compacta",
    "precio": 234,
    "stock": 0,
    "cpu": "Arm Cortex-A7 + coprocesador RISC-V",
    "nucleos": "1",
    "frecuencia_mhz": "1200",
    "ram": "64 MB DDR2",
    "flash": "128 MB SPI NAND (variante B) + microSD opcional (variante A)",
    "conectividad_principal": "Sin Wi-Fi/Bluetooth; USB 2.0 Host/Device",
    "perifericos": "MIPI CSI de 2 lanes; 17 GPIO; NPU de 0.5 TOPS (hasta 1.0 TOPS en INT4); ISP de hasta 4 MP con HDR/WDR/reducción de ruido",
    "ide": "Luckfox SDK, Buildroot, Ubuntu 22.04",
    "ficha": "Luckfox Pico Mini se basa en el SoC Rockchip RV1103 con núcleo Arm Cortex-A7 a 1.2 GHz y coprocesador RISC-V, junto a 64 MB de DDR2 integrada. Incluye NPU de 0.5 TOPS, ISP de hasta 4 MP con entrada MIPI CSI de 2 lanes y 17 GPIO; no integra radio inalámbrica.",
    "link": "https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-RV1103/"
  },
  {
    "id": "radxa-zero-3w",
    "sku": "HK-SBC-005",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Radxa",
    "familia": "Radxa ZERO",
    "familia_soc": "Rockchip RK3xxx",
    "nombre": "Radxa ZERO 3W",
    "imagen": "HI65",
    "soc": "Rockchip RK3566",
    "tipo": "SBC Linux/Android",
    "precio": 239,
    "stock": 0,
    "cpu": "Quad Arm Cortex-A55",
    "nucleos": "4",
    "frecuencia_mhz": "1600",
    "ram": "1/2/4/8 GB LPDDR4",
    "flash": "microSD + eMMC según configuración",
    "conectividad_principal": "Wi-Fi 6; Bluetooth 5.4",
    "perifericos": "micro HDMI; USB-C/USB; GPIO; interfaces de cámara/display según placa; GPU Mali-G52",
    "ide": "Radxa OS, Debian, Ubuntu, Android",
    "ficha": "Radxa ZERO 3W es una SBC compacta con RK3566 quad-core Cortex-A55 a hasta 1.6 GHz y opciones de 1 a 8 GB de LPDDR4. Incorpora Wi-Fi 6 y Bluetooth, salida HDMI, USB, GPIO y opciones de almacenamiento microSD/eMMC.",
    "link": "https://radxa.com/products/zeros/zero3w/"
  },
  {
    "id": "orange-pi-zero-2w",
    "sku": "HK-SBC-006",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Orange Pi",
    "familia": "Orange Pi Zero",
    "familia_soc": "Allwinner H618",
    "nombre": "Orange Pi Zero 2W",
    "imagen": "HI66",
    "soc": "Allwinner H618",
    "tipo": "SBC Linux/Android",
    "precio": 296,
    "stock": 0,
    "cpu": "Quad Arm Cortex-A53",
    "nucleos": "4",
    "frecuencia_mhz": "1500",
    "ram": "1/1.5/2/4 GB LPDDR4",
    "flash": "microSD/TF + 16 MB SPI Flash",
    "conectividad_principal": "Wi-Fi 5 dual-band 802.11a/b/g/n/ac; Bluetooth 5.0",
    "perifericos": "mini HDMI 2.0; USB Type-C; header de expansión de 40 pines y conector adicional; GPU Mali-G31 MP2",
    "ide": "Orange Pi OS, Android, Debian, Ubuntu",
    "ficha": "Orange Pi Zero 2W emplea Allwinner H618 quad-core Cortex-A53 a hasta 1.5 GHz, con 1 a 4 GB de LPDDR4, microSD y 16 MB de SPI Flash. Integra Wi-Fi dual-band 802.11ac, Bluetooth 5.0, HDMI, USB-C y expansión GPIO.",
    "link": "https://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero-2W.html"
  },
  {
    "id": "luckfox-pico-pro-max",
    "sku": "HK-SBC-007",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "LuckFox",
    "familia": "LuckFox Pico",
    "familia_soc": "Rockchip RV11xx",
    "nombre": "LuckFox Pico Pro / Max",
    "imagen": "HI67",
    "soc": "Rockchip RV1106G2 (Pro) / RV1106G3 (Max)",
    "tipo": "SBC Linux + NPU",
    "precio": 398,
    "stock": 0,
    "cpu": "Arm Cortex-A7 + coprocesador RISC-V",
    "nucleos": "1",
    "frecuencia_mhz": "1200",
    "ram": "128 MB DDR3L (Pro) / 256 MB DDR3L (Max)",
    "flash": "256 MB SPI NAND + microSD",
    "conectividad_principal": "Ethernet 10/100 Mb/s; sin radio integrado",
    "perifericos": "MIPI CSI; USB 2.0 host/device; 26 GPIO; NPU 0.5 TOPS (Pro) / 1 TOPS (Max)",
    "ide": "LuckFox SDK, Buildroot, Ubuntu 22.04",
    "ficha": "LuckFox Pico Pro y Max usan RV1106: Pro incorpora 128 MB DDR3L y NPU de 0.5 TOPS, mientras Max incorpora 256 MB y NPU de 1 TOPS. Ambos operan con Cortex-A7 a 1.2 GHz, 256 MB SPI NAND, Ethernet, cámara MIPI y microSD.",
    "link": "https://wiki.luckfox.com/Luckfox-Pico-Pro-Max/"
  },
  {
    "id": "milk-v-duo-s",
    "sku": "HK-SBC-008",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "Milk-V",
    "familia": "Duo",
    "familia_soc": "SOPHGO SG200x",
    "nombre": "Milk-V Duo S",
    "imagen": "HI68",
    "soc": "SOPHGO SG2000",
    "tipo": "SBC Linux/RTOS + TPU",
    "precio": 489,
    "stock": 0,
    "cpu": "RISC-V C906 + Arm Cortex-A53 seleccionable + 8051",
    "nucleos": "2",
    "frecuencia_mhz": "1000",
    "ram": "512 MB SiP DRAM",
    "flash": "microSD + pads eMMC",
    "conectividad_principal": "Ethernet 100 Mb/s onboard; Wi-Fi 6 + Bluetooth 5 opcional",
    "perifericos": "C906 principal 1 GHz; C906 secundario 700 MHz; A53 alternativo 1 GHz; USB-C/USB host; MIPI CSI/DSI; hasta 39 GPIO; TPU 0.5 TOPS",
    "ide": "Milk-V SDK, Linux, RTOS",
    "ficha": "Milk-V Duo S usa SG2000 con 512 MB de DRAM. Combina C906 RISC-V, un Cortex-A53 seleccionable para el núcleo principal y otro C906 a 700 MHz, además de un 8051. Incluye Ethernet 100 Mb/s, interfaces MIPI, USB y TPU de 0.5 TOPS; Wi-Fi 6/Bluetooth es opcional.",
    "link": "https://milkv.io/duo-s"
  },
  {
    "id": "nanopi-neo3",
    "sku": "HK-SBC-009",
    "seccion": "mcu",
    "categoria": "Placas Linux / SBC",
    "marca": "FriendlyELEC",
    "familia": "NanoPi",
    "familia_soc": "Rockchip RK3xxx",
    "nombre": "NanoPi NEO3",
    "imagen": "HI69",
    "soc": "Rockchip RK3328",
    "tipo": "SBC Linux",
    "precio": 507,
    "stock": 0,
    "cpu": "Quad Arm Cortex-A53",
    "nucleos": "4",
    "frecuencia_mhz": "1300",
    "ram": "1/2 GB DDR4",
    "flash": "microSD",
    "conectividad_principal": "Gigabit Ethernet; sin Wi-Fi/Bluetooth integrado",
    "perifericos": "USB 3.0 Type-A; USB 2.0 en header; header GPIO de 26 pines; I2C/UART/SPI/I2S; USB-C power; UART de depuración",
    "ide": "FriendlyWrt, FriendlyCore/Ubuntu, Debian",
    "ficha": "NanoPi NEO3 es una SBC de 48×48 mm basada en RK3328 quad-core Cortex-A53 a hasta 1.3 GHz, con 1 o 2 GB DDR4. Incluye Gigabit Ethernet, USB 3.0, microSD y header GPIO de 26 pines; no integra Wi-Fi ni Bluetooth.",
    "link": "https://wiki.friendlyelec.com/wiki/index.php/NanoPi_NEO3"
  },
  {
    "id": "stm32-nucleo-h753zi",
    "sku": "HK-STM-002",
    "seccion": "mcu",
    "categoria": "Arduino / STM32",
    "marca": "STMicroelectronics",
    "familia": "Nucleo",
    "familia_soc": "STM32",
    "nombre": "STM32 NUCLEO-H753ZI",
    "imagen": "HI70",
    "soc": "STMicroelectronics STM32H753ZI",
    "tipo": "Nucleo-144 MCU alto rendimiento",
    "precio": 591,
    "stock": 0,
    "cpu": "Arm Cortex-M7",
    "nucleos": "1",
    "frecuencia_mhz": "480",
    "ram": "1 MB RAM",
    "flash": "2 MB Flash",
    "conectividad_principal": "Ethernet 10/100 Mb/s; sin radio",
    "perifericos": "ST Zio/Arduino y ST Morpho; ST-LINK; Ethernet; USB OTG FS; GPIO y periféricos avanzados; conectores de expansión",
    "ide": "STM32CubeIDE, STM32CubeMX, IAR, Keil",
    "ficha": "NUCLEO-H753ZI incorpora STM32H753ZI, un único Cortex-M7 a hasta 480 MHz con 2 MB de Flash y 1 MB de RAM. La Nucleo-144 ofrece ST-LINK, headers Zio/Morpho, Ethernet y USB para evaluación del amplio conjunto de periféricos del H753; no integra Wi-Fi/Bluetooth.",
    "link": "https://www.st.com/en/evaluation-tools/nucleo-h753zi.html"
  },
  {
    "id": "arduino-giga-r1-wifi",
    "sku": "HK-ARD-002",
    "seccion": "mcu",
    "categoria": "Arduino",
    "marca": "Arduino",
    "familia": "Arduino GIGA",
    "familia_soc": "STM32",
    "nombre": "Arduino GIGA R1 WiFi",
    "imagen": "HI71",
    "soc": "STMicroelectronics STM32H747XI",
    "tipo": "Placa Arduino dual-core de alto rendimiento",
    "precio": 830,
    "stock": 0,
    "cpu": "Arm Cortex-M7 + Cortex-M4",
    "nucleos": "2",
    "frecuencia_mhz": "480 / 240",
    "ram": "1 MB SRAM interna + 8 MB SDRAM",
    "flash": "2 MB Flash interna + 16 MB Flash externa",
    "conectividad_principal": "Wi-Fi; Bluetooth mediante módulo Murata 1DX",
    "perifericos": "76 I/O; entradas analógicas y DAC; USB-C device/HID; USB-A host; jack de audio; conectores de cámara/display; UART/I2C/SPI/CAN",
    "ide": "Arduino IDE, Arduino Cloud, MicroPython",
    "ficha": "Arduino GIGA R1 WiFi usa STM32H747XI dual-core: Cortex-M7 a 480 MHz y Cortex-M4 a 240 MHz. Integra 1 MB de SRAM y 2 MB de Flash en el MCU, más 8 MB SDRAM y 16 MB de Flash externas, junto con Wi-Fi/Bluetooth, abundantes I/O, USB host/device, audio y conectores multimedia.",
    "link": "https://docs.arduino.cc/hardware/giga-r1-wifi"
  },
  {
    "id": "arduino-portenta-h7-lite",
    "sku": "HK-ARD-003",
    "seccion": "mcu",
    "categoria": "Arduino",
    "marca": "Arduino",
    "familia": "Portenta",
    "familia_soc": "STM32",
    "nombre": "Arduino Portenta H7 Lite",
    "imagen": "HI72",
    "soc": "STMicroelectronics STM32H747XI",
    "tipo": "Módulo Arduino dual-core alto rendimiento",
    "precio": 902,
    "stock": 0,
    "cpu": "Arm Cortex-M7 + Cortex-M4",
    "nucleos": "2",
    "frecuencia_mhz": "480 / 240",
    "ram": "1 MB SRAM interna + 8 MB SDRAM",
    "flash": "2 MB Flash interna + 16 MB QSPI Flash",
    "conectividad_principal": "Sin Wi-Fi/Bluetooth",
    "perifericos": "Ethernet PHY; USB-C; dos conectores de alta densidad de 80 pines; cámara y buses de alta velocidad; elemento seguro",
    "ide": "Arduino IDE, Mbed OS, MicroPython",
    "ficha": "Portenta H7 Lite conserva el STM32H747XI dual-core a 480/240 MHz y la memoria externa de la familia Portenta H7, pero elimina el módulo Wi-Fi/Bluetooth. Ofrece USB-C, Ethernet mediante PHY, conectores de alta densidad y recursos para aplicaciones industriales/embebidas.",
    "link": "https://docs.arduino.cc/hardware/portenta-h7-lite"
  },
  {
    "id": "arduino-portenta-h7",
    "sku": "HK-ARD-004",
    "seccion": "mcu",
    "categoria": "Arduino",
    "marca": "Arduino",
    "familia": "Portenta",
    "familia_soc": "STM32",
    "nombre": "Arduino Portenta H7",
    "imagen": "HI73",
    "soc": "STMicroelectronics STM32H747XI",
    "tipo": "Módulo Arduino dual-core alto rendimiento",
    "precio": 1296,
    "stock": 0,
    "cpu": "Arm Cortex-M7 + Cortex-M4",
    "nucleos": "2",
    "frecuencia_mhz": "480 / 240",
    "ram": "1 MB SRAM interna + 8 MB SDRAM",
    "flash": "2 MB Flash interna + 16 MB QSPI Flash",
    "conectividad_principal": "Wi-Fi 802.11b/g/n; Bluetooth 5.1 mediante Murata 1DX",
    "perifericos": "Ethernet PHY; USB-C con DisplayPort; dos conectores de alta densidad de 80 pines; cámara; buses de alta velocidad; elemento seguro",
    "ide": "Arduino IDE, Mbed OS, MicroPython, Arduino Cloud",
    "ficha": "Portenta H7 integra STM32H747XI con Cortex-M7 a 480 MHz y Cortex-M4 a 240 MHz, además de 8 MB SDRAM y 16 MB QSPI Flash externos. El módulo Murata 1DX añade Wi-Fi y Bluetooth 5.1; también incluye USB-C/DisplayPort, Ethernet PHY y conectores de alta densidad.",
    "link": "https://docs.arduino.cc/hardware/portenta-h7"
  }
];
